version: 2
updates:
    # Maintain python dependencies
    package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
    commit-message:
      prefix: "build"
      include: "scope"
