
[tool.commitizen]
name = "cz_conventional_commits"
version = "2.0.0"
tag_format = "v$version"
update_changelog_on_bump = true
version_files = [
  "pyproject.toml:version",
]

[tool.poetry]
name = "dramatiq_azure"
version = "2.0.0"
description = "Azure Queue Brokers for Dramatiq"
authors = ["Stanislas H.B. Sodonon <stanislas.sodonon@gmail.com>"]
repository = "https://github.com/bidossessi/dramatiq-azure"
readme = 'README.md'
keywords = ['dramatiq', 'azure', 'queue', 'broker']
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.10"
dramatiq = "^2.0.0"
azure-core = "^1.36.0"
azure-storage-queue = "^12.14.1"
azure-identity = {version = "^1.25.1", optional = true}

[tool.poetry.group.dev.dependencies]
pytest = "^8.2.1"
pytest-cov = "^7.0.0"
mypy = ">=1.11,<3.0"
pytest-env = "^1.1.3"
commitizen = "^4.7.0"
pre-commit = ">=3.8,<5.0"
pytest-mock = "^3.14.0"
ruff = "^0.16.5"

[tool.poetry.extras]
identity = ["azure-identity"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 80

[tool.ruff.format]
exclude = ["*.md"]

[tool.ruff.lint]
select = ["B", "C90", "E", "F", "I", "W"]

[tool.ruff.lint.mccabe]
max-complexity = 10

[tool.ruff.lint.isort]
combine-as-imports = true
