on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: CI

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Azurite
        id: azuright
        uses: potatoqualitee/azuright@v1.1
      - name: Install poetry
        run:  curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -
      - name: Install dependencies
        run: poetry install
      - name: Lint code
        uses: psf/black@stable
      - name: Run Tests
        run: poetry run pytest
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage.xml
